spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/financesuserdbdev
    username: postgres
    password: 1234567
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false


