spring:

  datasource:
    url: jdbc:postgresql://prod-db-server:5432/financesuserdb
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect