spring:
  profiles:
    active: dev

  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    schemas: financesuserdb
    user: root
    password: 123456