spring:
  application:
    name: ms-finances-users

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@finances.ol6kb.mongodb.net/?retryWrites=true&w=majority&appName=finances
      database: financesdbdev

admin-credentials:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

server:
  port: 8100
